### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by craciunchan** [liamjack/VirtualTrader#1]
hello,how to fix it?
Warning: Cannot modify header information - headers already sent by (output started at /home/vipsmzpx/public_html/mycoinreview.com/scripts/VirtualTrader-master/inc/config.php:31) in /home/vipsmzpx/public_html/mycoinreview.com/scripts/VirtualTrader-master/index.php on line 70

**Comment by Georift** [comment]
You can change line 70 of index.php to the following:

``` php
@header("Location: ?page=home");
echo "<script>window.location=\"index.php?page=home\";</script>";
```

The @ should suppress the warning and the JavaScript should redirect the page. I haven't tested this but fairly certain it will work.

**Comment by craciunchan** [comment]
now after login 
what is the admin details

Warning: Cannot modify header information - headers already sent by (output started at /home/vipsmzpx/public_html/mycoinreview.com/scripts/VirtualTrader-master/inc/config.php:31) in /home/vipsmzpx/public_html/mycoinreview.com/scripts/VirtualTrader-master/inc/auth.class.php on line 278

Warning: Cannot modify header information - headers already sent by (output started at /home/vipsmzpx/public_html/mycoinreview.com/scripts/VirtualTrader-master/inc/config.php:31) in /home/vipsmzpx/public_html/mycoinreview.com/scripts/VirtualTrader-master/pages/login.php on line 42
