### ISSUE TITLE
Unable to load pages

### ISSUE THREAD

**Issue by jackluo** [liamjack/VirtualTrader#2]
Hey Liam,

Not sure if you're still working on this. 
I've tried using your app on a local AMP server, and set the homepage to index.php with parameter ?page=home, prompting the user to login/register. However after that step the whole app is blank.
If you are still involved in this project, I'd love if you could give me a hand :) 

Thanks
Jack

**Comment by liamjack** [comment]
Hey Jack,
Geez, this dates back from 4 years ago, but hey I'll help you out.
Normally if there is a problem PHP should display errors, check that
you display errors, and that you display E_ALL in your php.ini.After
doing that the page should no longer be blank and might show you what's
wrong.
Liam
Le samedi 05 novembre 2016 à 12:49 -0700, Jack (Wei Xi) Luo a écrit :
